## Environment Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Mod Properties
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.19.3)
forge_version=43.5.0
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=official
mapping_version=1.19.2

mod_id=fluidrouterupgrade
mod_name=FluidRouterUpgrade
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.yuuhamu.fluidrouterupgrade
mod_authors=yuuhamu
mod_description=Vanilla ModularRoutersのRouterにFluid Mode Upgradeを挿すだけで、Forge Fluid(バケツ等)の転送に対応させるアドオンMOD。RouterUpgradeCoreに必須依存する。

## 依存Modのバージョン(Modrinthのバージョン番号)
modularrouters_version=1.19.2-10.2.1
routerupgradecore_version=0.1.0

jei_version=11.39.0.1068
